#!/bin/bash
# Here put anything that is needed to start the service.
# Note that currently this is run directly after install
# i.e. 'service apache2 start'
PORT=`config-get port`

if [ ! -f /root/.vegas/genghisapp/genghisapp.pid ] ; then
	HOME=/root genghisapp -L -p $PORT
fi

open-port $PORT
